APPL_COBJS += \
	ActionController.o \
	RequestwaitController.o \
	DeliveryController.o \
	LineDriveController.o \
	ButtonUnit.o \
	DisplayUnit.o \
	HornUnit.o \
	LineMonitorUnit.o \
	LuggageCarrierUnit.o \
	MotorUnit.o \
	TimerUnit.o \
	WallMonitorUnit.o
