APPL_COBJS += \
	ActionController.o \
	RequestwaitController.o \
	CollectmoveController.o \
	CarrywaitController.o \
	CarryremindController.o \
	CollectturnController.o \
	DeliveryController.o \
	DropbuggageController.o \
	LineDriveController.o \
	ButtonUnit.o \
	DisplayUnit.o \
	HornUnit.o \
	LineMonitorUnit.o \
	LuggageCarrierUnit.o \
	MotorUnit.o \
	TimerUnit.o \
	WallMonitorUnit.o \
	TurnleftController.o \
	TurnrightController.o \
	UnloadwaitController.o \
	UnloadremindController.o

